### ISSUE TITLE
Cookie data syntax - white space in Cookie banner code

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1097]
When setting the cookie, the semi colon has a space before it, instead of after it so this
`document.cookie = "noEnhancedAnalytics=1 ;max-age=2592000 ;domain=" + domain;
`
Should be this:
`document.cookie = "noEnhancedAnalytics=1; max-age=2592000; domain=" + domain;`

Please update across all 360Giving tools that use the Universal Cookie banner

**Comment by michaelwood** [comment]
Some browsers seem to be parsing the cookie data with a semi-colon **and** a space rather than just a semi-colon, so we need to change this to either omit the white space or add it after the semi-colon [as suggested](https://github.com/ThreeSixtyGiving/grantnav/issues/1097#issue-2489215579). 

This works:
`"noEnhancedAnalytics=1;max-age=2592000;domain=threesixtygiving.org" `
or as suggested
`"noEnhancedAnalytics=1; max-age=2592000; domain=threesixtygiving.org" `

https://www.rfc-editor.org/rfc/rfc6265#section-4.2.1

**Comment by michaelwood** [comment]
Fixed and now live - https://github.com/ThreeSixtyGiving/grantnav/commit/d28720523befca13533af23a17a9fba3c2938bcc
