### ISSUE TITLE
Comma separators - funders table  

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#343]
The table for funders: http://grantnav.threesixtygiving.org/funders - the count for grants is missing commas

**Comment by morchickit** [comment]
@robredpath - I believe this is a very small fix to do, can we do it if we have time?

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav - add commas to funders table](https://trello.com/c/CtHkumRn/70-grantnav-add-commas-to-funders-table)

**Comment by robredpath** [comment]
@morchickit IIRC this is actually one of those annoying things where it's a bigger job than it should be - the library that we're using for the tables has predefined types and the 'count' type doesn't have commas while the 'currency_amount' (I think!) type does. So, adding those commas involves hacking around with the library. 

It's been ages since we looked into this though, so it may well be easier with a newer version of the lib.
