### ISSUE TITLE
GrantNav sums values, regardless of currency, into GBP totals

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#387]
There is an issue with the totals, such as

![billions](https://user-images.githubusercontent.com/1209944/27447807-6068ddbc-577a-11e7-8a0c-cfe648af079a.png)

The GBP figure - we assume - is a total of the AmountAwarded field, but not considering values in other currencies.

We should clarify this before discussing action --> @robredpath please can you check?

**Comment by robredpath** [comment]
I've just tested this a bit further and that's correct - we're assuming that all grants are in GBP before summing

**Comment by stevieflow** [comment]
Thanks @robredpath 

I guess the options could then be:

- only SUM GBP values (*add something to GN to say non GBP values are excluded)
- convert non GBP values, using exchange rate (API) on Award Date
- scrap all such sums

Any other possibilities?

cc/ @morchickit @KDuerden

**Comment by morchickit** [comment]
Conversion is an issue (since the day of awarded and day of the transaction are not the same). Can we look and see how many non GBP grants are we speaking about?

**Comment by stevieflow** [comment]
I think there are 564 USD grants in the current corpus: http://grantnav.threesixtygiving.org/stats

**Comment by stevieflow** [comment]
They mainly seem to be from one publisher, too: http://grantnav.threesixtygiving.org/stats?text_query=currency%3D%22usd%22

**Comment by morchickit** [comment]
Ok, that is less that 1% of the grants, so I think we should go with option 1, SUM only GBP values. We should make sure that we sign post that 564 grants are missing since they are in USD. Maybe we can just present somewhere the sum in USD?

**Comment by KDuerden** [comment]
there will be EUR and CHF next month too.

**Comment by stevieflow** [comment]
@robredpath when you've time, can you check for other currencies ?  (NOT GBP query)

@morchickit that could be a possibility.  We should be minded that overnight any publisher could switch / add data to a new currency - EUR, for example.  In other words, whilst the USD story is minor now, that's only based on who is published "right now*... we probably want to avoid:

![giphy 7](https://user-images.githubusercontent.com/1209944/27492929-e1238694-583f-11e7-926c-654c585536ae.gif)

**Comment by morchickit** [comment]
Indeed, but then we have to think how to solve the conversion rate issue... :-) (oh, are we back at the start again?) 

Anyway, let's just do GBP for now and sign post that there are others not in GBP

**Comment by KDuerden** [comment]
if it's any comfort conversion rate & timing is real world issue for funders of multiple currencies - awards and payments being often months apart, who takes the hit or benefits when things change etc.

**Comment by robredpath** [comment]
When the time comes, we can look at options of how we explore this in GrantNav - I'm sure that a little bit of UI design will go a long way. 

Exchange rates are a live issue for Open Contracting as well - see https://github.com/open-contracting/standard/issues/384 for the kind of standards fun you can have around them!

**Comment by morchickit** [comment]
Connected to #380

**Comment by stevage** [comment]
@stevieflow 

>Any other possibilities?

Separately sum each currency:

```
Total awarded:
  512,345 EUR
  14,191 USD
  300 AUD

```

**Comment by stevieflow** [comment]
@stevage that's a good (and obvious one I didnt think of) suggestion.  @morchickit ?

**Comment by robredpath** [comment]
@stevage @stevieflow @morchickit We did think about that option recently - it's relatively easy to design for a fixed number of currencies, but would need a bit more work to make it work for any number of currencies. (eg if there are more than x currencies, it switches to "There are X grants in Y currencies, click here to see" - but with better microcopy, obviously)

**Comment by robredpath** [comment]
We're going to make Elastic return the aggregate figures by currency (Elastic call it a histogram search). Initially we're going to only show the GBP in the UI, but doing it this way means that we can try to show other currencies as well. 

We're going to rearrange the aggregate figures to separate out the currency bits, and add a 'total grants in GBP' stat so that secondary calculation of averages makes sense.

**Comment by stevieflow** [comment]
It'll also be useful to know how this will interact with functionality proposed in https://github.com/OpenDataServices/grantnav/issues/380#issuecomment-355572567

**Comment by morchickit** [comment]
Cool, is this means we will have a facet name Currency?

**Comment by morchickit** [comment]
Never mind, I read #380. Ignore me! :-)

**Comment by robredpath** [comment]
@stevieflow At a minimum we'll make the summary stats just show the stats for the GBP grants in the search results (excluding non-GBP from stats) with a warning to say what we've done. We're intending to design some UI to show other currencies meaningfully. I hadn't thought about what we do if the currency is set to, for example, USD. We should probably make the summary stats be just USD, but we haven't worked that through yet.

**Comment by robredpath** [comment]
![screen shot 2018-01-10 at 16 45 44](https://user-images.githubusercontent.com/641009/34784310-d3aff52c-f625-11e7-8ab7-2bc97c4ac44b.png)

@kindly - just to check we're on the same page, I mocked up some UI that I think matches our conversation earlier in the week. Does that look right to you? 

Also - see my comment above - I think we need to make it so that if the Amount Awarded facet has a currency selected, the summary data uses that currency. 

@stevieflow @morchickit - how much do we care about currency symbols? Currently, we don't really have mapping set up (eg USD -> $), as values are either in £, or not (and we use their currency code). Adding full mapping is an extra bit of complexity - but I think that retaining £ for GBP isn't a big deal (if @kindly can confirm?).

**Comment by morchickit** [comment]
I don't see the symbols as a big issue, especially when $ is applicable to
so many countries (AUS, CAD, etc...)

**Comment by stevieflow** [comment]
If we choose to display a $ then we should certainly include the currency code (USD, CAN, AUD etc).

**Comment by kindly** [comment]
Started some work on this and it looks like this:

![grantnav search stats](https://user-images.githubusercontent.com/30636/34795020-89b1f394-f648-11e7-918b-cd1297d11cad.png)

We can have currency symbols for the currencies we know about and leave them out if not, just will take us compiling a small list of mappings. We should keep the codes in anyway because of the multi  use of '$'

After clicking on the non-GBP currency number you will get a list of all the currencies in a modal block (not implemented yet)

@robredpath  The way that makes most sense (in terms of the code at least) is having the 
summary box show the most common currency (most grants) in the current search. If you facet on another currency (say USD) in Amount Awarded then this will therefore show USD in the summary box.  This feels more consistent to me as  if you put "currency:USD" in the search box you will also get USD in the summary box. It also makes grantnav less GBP centric.  The downside is that you do a query that you don't expect the most results to be USD you might be irritated by having to click on the non-USD box to get GBP values (but that should be rare with the current data).  How does that sound?

**Comment by robredpath** [comment]
Looks great, thanks @kindly 

I think that with the current data set you will almost always get GBP being the most common currency, so it's not a big deal. It may even serve as an alert to users that their search results are tending towards USD, which they may not otherwise notice. If we do get people hitting it, we can always add a "why am I seeing this?" help link.

**Comment by kindly** [comment]
![with_model](https://user-images.githubusercontent.com/30636/34829321-3a881a9c-f6d8-11e7-8e9e-7bbdde949cbe.png)

This above is done in [this pull request](https://github.com/OpenDataServices/grantnav/pull/428)

The currencies are sorted by most grants that appear first.

**Comment by Bjwebb** [comment]
Dev instance to test this: http://current.acceptable-license-valid.387-sum-currencies.grantnav-dev.default.threesixtygiving.uk0.bigv.io/

**Comment by Bjwebb** [comment]
I have the option to open the non-GBP link in a new tab, but when I do I just get a copy of the page I'm on. Can we disable this?

**Comment by kindly** [comment]
@Bjwebb Have done this.

Also made the the number not a link when javascript is disabled.
Not perfect, as it reduces functionality for non javascript users, but a lot simpler then creating another page just for this small model.

**Comment by Bjwebb** [comment]
That looks good, thanks.

**Comment by morchickit** [comment]
@robredpath - can you confirm we can close this?
