### ISSUE TITLE
Make GrantNav work with elastic 7

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#510]
- Use file-based loading to start; not connected to PG
- See how much it works, see what the differences are
- Deploy to a dev server
- Look into an alternative to the stats page - check with @KDuerden about how its used

**Comment by robredpath** [comment]
Logging issues reported in testing

> - there are some duplicate grants eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/grant/360G-blf-0030009769 - this isn't a duplicate on the current GrantNav. This has a variety of knock-on impacts - like the counts on the first page - the same number of funders but 74,000 more grants in the test version
> - I'm getting an exception for some of the datatable downloads - eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/funders_datatables.csv and http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/funder_recipients_datatables.json
> - The National Lottery Community Fund is showing under it's old name The Big Lottery Fund (can't remember how this has been changed in the current one)
> - Some tables are displaying NaN in the summary eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/district/Mendip%20District

@michaelwood if any of these prove to be difficult to work through or need their own issues, do break them out and track them separately

**Comment by michaelwood** [comment]
- Datasets table here appears to be empty: http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/datasets/

**Comment by Bjwebb** [comment]
Note that datasets table probably isn't an ES7 issue, as it gets read from a separate JSON file, see https://github.com/ThreeSixtyGiving/grantnav#provenance-json

**Comment by michaelwood** [comment]
> * Datasets table here appears to be empty: http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/datasets/

Now fixed via https://github.com/ThreeSixtyGiving/datastore/issues/8

**Comment by michaelwood** [comment]
(MW to ping David R on outstanding issues  to pair up on fixing it)

**Comment by michaelwood** [comment]
For the bucket size issue on  [funder_recipients_datatables.json](http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/funder_recipients_datatables.json) we will need to set search.max_buckets using the Update [Cluster Settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html) 658 API. I don't see any obvious place to do this as I don't think we have any other settings currently. Will consult on where a logical place for this would be.

**Comment by michaelwood** [comment]
Seem to have summing error on the total number of Funders, or some aren't being show in the funders table. http://current.acceptable-license-valid.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/ headline says 109 clicking through to the funders table shows 107.

**Comment by KDuerden** [comment]
The funders list via /funders view always excludes non-GBP funders, Arcadia and Quixote. In current live GN, it's 111 on the homepage but 110 in the list (cos Quixote fell out when their data was down).

**Comment by michaelwood** [comment]
> Logging issues reported in testing
> 
~~> > * there are some duplicate grants eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/grant/360G-blf-0030009769 - this isn't a duplicate on the current GrantNav. This has a variety of knock-on impacts - like the counts on the first page - the same number of funders but 74,000 more grants in the test version~~

Haven't seen this issue crop up recently but we have split it out into https://github.com/ThreeSixtyGiving/datastore/issues/11

~~> > * I'm getting an exception for some of the datatable downloads - eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/funders_datatables.csv and http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/funder_recipients_datatables.json~~

Should be fixed now with https://github.com/OpenDataServices/opendataservices-deploy/blob/mw/360_datastore/salt/grantnav-es7.sls#L26 which is deployed to the latest.es7.grantnav server

~~> >   ~- The National Lottery Community Fund is showing under it's old name The Big Lottery Fund (can't remember how this has been changed in the current one)~ see #512~~

Separated into a new issue https://github.com/ThreeSixtyGiving/datastore/issues/7

> > * Some tables are displaying NaN in the summary eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/district/Mendip%20District

Note to self we are sending back "recordsTotal: {"value": 3, "relation": "eq"} " instead of a flat value on the ajax call instead of a flat value such as recordsTotal:  3

**Comment by michaelwood** [comment]
> Some tables are displaying NaN in the summary eg http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/district/Mendip%20District
Note to self we are sending back "recordsTotal: {"value": 3, "relation": "eq"} " instead of a flat value on the ajax call instead of a flat value such as recordsTotal: 3

Issue now fixed, deployed to dev.
