### ISSUE TITLE
Add more fields that we add in the Datastore into GrantNav

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#574]
- It's clear how the world will be different when the work is completed

A selection of fields from the ones that we add in the datastore will be included in the grant display in GrantNav

- It's clear what will and won't be done

This will only be fields that we already generate; nothing new. 

- Any uncertainty, assumptions, dependencies or constraints are recorded

- There's an order-of-magnitude estimate of how long it will take

- The work's been approved by someone at ThreeSixtyGiving

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

**Comment by drkane** [comment]
Some thoughts on the fields it would be useful to include:

 - geographical data, replacing the ones that are used previouly - the first field from `additionalData->locationLookup` is the best to use here.
 - organisation details - we'd like to have a canonical name for organisations, rather than taking the first one found in the data. So for example this record: http://grantnav.threesixtygiving.org/recipient/GB-EDU-133801 is Cambridge University. There's a [slightly convuluted process in the covid tracker](https://github.com/ThreeSixtyGiving/covid19-tracker/blob/master/covidtracker/fetch_data.py#L19-L42) for working out which of the names is canonical from`recipientOrgInfos`.

Alongside the canonical name it would also be possible to add organisation type and size from this as potential facets for the data.

**Comment by robredpath** [comment]
Sprint checkin 2020-11-09 - we'll probably add the canonical naming stuff into the data store, and then pull it into GN. This does further reduce GN's independence, but does help us keep uniformity.

**Comment by drkane** [comment]
One other field I forgot - the funding Organisation type field we recently added.

**Comment by michaelwood** [comment]
Work is done on the datastore side: https://github.com/ThreeSixtyGiving/datastore/pull/65 
We're just going to include all the additional_data fields and filter at the GN end if needed.
