### ISSUE TITLE
Work out how to display additional fields from the data store on the grant page

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#596]
The data store adds a lot of additional fields to each grant record. 

We should:
* Work out which of these we want to display on the grant page
* Work out how we want to display these (eg a separate table?) 

We should also look at whether we include the fields in the grant record that are currently broken out to form the top of the grant page, in the table. This would help users understand that the data is part of the grant record, and know what the fields are called.

**Comment by robredpath** [comment]
List of fields is at https://github.com/ThreeSixtyGiving/datastore/issues/72 . 

You can see this in action at http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/grant/360G-Walcot-00680000013b2mcAAA 

My initial suggestion is that we:
* remove the 'additional data added by GrantNav' table, because there isn't any
* Add a table for additional fields that we want to highlight, add descriptions for them, and make it configurable (So, for example, we might select "additional_data: TSGFundingOrgType" for inclusion in the table, and add a description)
* Add a third table, collapsed by default (new component klaxon!) which contains the rest of the data, and makes reference to the datastore, with a link to the datastore page on the 360 website. 

Thoughts @michaelwood @drkane ?

**Comment by drkane** [comment]
@robredpath that sounds great to me - I like the idea of highlighting particular parts, eg it probably makes sense to have a "location" table.

I'm not sure if the third table is necessary or not - it might be confusing, even if collapsed. I think it's fine to just highlight the additional data that's interesting or relevant and drop the rest. The only issue would be if it's being indexed & searched but then not shown in the grant page.

**Comment by michaelwood** [comment]
> 
> * remove the 'additional data added by GrantNav' table, because there isn't any

Just fyi, the table is currently empty because current-sprint grantnav doesn't know what fields are additional anymore. The listing here https://github.com/ThreeSixtyGiving/grantnav/blob/master/grantnav/frontend/templatetags/frontend.py#L58 is not in sync with the data.

> * Add a table for additional fields that we want to highlight, add descriptions for them, and make it configurable (So, for example, we might select "additional_data: TSGFundingOrgType" for inclusion in the table, and add a description)
> * Add a third table, collapsed by default (new component klaxon!) which contains the rest of the data, and makes reference to the datastore, with a link to the datastore page on the 360 website.
> 
> Thoughts @michaelwood @drkane ?

Sounds fine to me, would the collapsed table also need descriptions /names for each field? as there are huge number of them...

**Comment by robredpath** [comment]
@michaelwood as I understand it, the additional data is no longer added by GrantNav, but the data store. Is there still anything that we're doing in GN?

**Comment by michaelwood** [comment]
> @michaelwood as I understand it, the additional data is no longer added by GrantNav, but the data store. Is there still anything that we're doing in GN?

So it's a yes and no! As of what is live today the additional data on the datastore isn't being exported to GN. That is waiting for the current-sprint GN to be live and the datastore part of that to be live too: https://github.com/ThreeSixtyGiving/datastore/pull/65

In the grantnav dataloader we check if the additional_data block has been added to the grant: https://github.com/ThreeSixtyGiving/grantnav/blob/master/dataload/import_to_elasticsearch.py#L301

If it isn't present GN has a go at it itself using the legacy methods... We may want to remove that mechanism for clarity, or at least tidy it up. It was left in there mainly so that people could do datagetter -> grantnav vs datastore -> grantnav.  It would probably be better to remove that code and degrade gracefully (which will be easier to do now that all the additional data fields are in one `additional_data` block instead of being mixed with the grant's orginal data.

**Comment by robredpath** [comment]
For the current sprint, we're just going to pull out the fields that we use to power facets. 

In the future, we can list out all of the datastore fields through some kind of expander.

**Comment by robredpath** [comment]
As the stop-gap, we can split the additional data object into its own table, with some description of what the table is about. Ideally, with some sort of expander / toggle
