### ISSUE TITLE
Funders Page - improvements

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#627]
- longer table?
- descriptive text 
- design!

**Comment by robredpath** [comment]
Also applies to Recipients and region pages

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav summary pages](https://trello.com/c/VMO0SMgO/155-grantnav-summary-pages)

**Comment by odscjames** [comment]
> longer table?

By this you mean the data tables have 400px height and they should have more? How much more? Hard to judge as if they have more height than the user has on their device I can see that being annoying to use.

**Comment by robredpath** [comment]
@odscjames yeah, I can see that - can we size it dynamically? Or, just reduce the space between the table and the footer? I think it's the presence of the white space there which makes it look wrong. On my iPad there's a little bit of white between the table and the footer, and it looks fine.

**Comment by odscjames** [comment]
> yeah, I can see that - can we size it dynamically?

Because it's powered by a JS widget ( https://datatables.net/reference/option/scrollY ) I think the best we can do is pass 80vh to it, maybe 70vh, so it's a % of page height. That gives the user the chance to centre it in their screen and see the most possible data at once.

> Or, just reduce the space between the table and the footer? I think it's the presence of the white space there which makes it look wrong.

A spacer-10 is explicitly added - we could make that a 4 or something.

**Comment by mariongalley** [comment]
I think this is solved by the new org page
