### ISSUE TITLE
Links in "where is this data from" on grant page aren't styled as links

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#642]

**Comment by stevieflow** [comment]
Yes - this should be fixed - it's not very intuitive or accessible to present things in the current way

![360Giving-GrantNav (1)](https://user-images.githubusercontent.com/1209944/112973902-ba598080-9149-11eb-95e9-930fa750454c.png)

I would suggest this has to be higher than low priority, also

**Comment by BibianaC** [comment]
What are the links?

**Cabinet office**: https://www.gov.uk/government/organisations/cabinet-office

**GrantNave publisher page**:
http://grantnav.threesixtygiving.org/recipient/360G-cabinetoffice-org%3AFCO---Internal---1866
or
http://grantnav.threesixtygiving.org/recipient/360G-cabinetoffice-GGIS_ID_50

**Comment by BibianaC** [comment]
![Screen Shot 2021-03-31 at 13 59 32](https://user-images.githubusercontent.com/9610927/113148108-61611980-9229-11eb-93d0-e8182c01398a.png)

The `text-decoration: none;` that is in `theme.css` should be disabled as it is above on the `Funding/Recipient organization` links. I don't see the difference that makes one work and the other one not.

If we want all the links to be underlined then we can just delete it from `theme.css` but it might be that in other parts of the website we do want the text decoration to be none.

Any thoughts @michaelwood @Lathrisk ?

**Comment by Lathrisk** [comment]
`theme.css` is now generated from the `scss` files, so deleting it there means it will get overwritten the next time we generate that file.

This particular rule is in `_reset.scss`, the purpose of which is usually to standardise styling across browsers and remove unwanted defaults. A better approach might be to create a new rule that targets the links and applies the relevant styling - [`custom.scss`](https://github.com/ThreeSixtyGiving/grantnav/blob/bfb0a7db8e557e8a3aa139592ee29615f7cc955d/grantnav/frontend/sass/custom.scss) is probably the best place for that.

**Comment by drkane** [comment]
I think this might need some changes to the design system CSS - it looks like the `var(--colors-alt)` value is wrong, it should be one of the main color vars.

On the underline - originally the style guide didn't have any underlines for links, which I don't think it very accessible. So we've been adding them back in, but the default is still for links to not be underlined. I think eventually we should swap this around so the default is for underline and we switch it off where not needed.

I'll make the change in the design system so that links in boxes use the right colour and are bold and underlined.

**Comment by drkane** [comment]
I've made [some changes to the design system](https://github.com/ThreeSixtyGiving/360-ds/commit/881bff7c94c470c7c216bcc42c21961d319aeca5) that should make the links more prominent in boxes.

**Comment by michaelwood** [comment]
I've deployed some other fixes and @BibianaC was included in the latest update. Now closing.
