### ISSUE TITLE
HTML tags appear in website

### ISSUE THREAD

**Issue by BibianaC** [ThreeSixtyGiving/grantnav#693]
![Screen Shot 2021-05-26 at 12 04 56](https://user-images.githubusercontent.com/9610927/119649538-a5802d00-be1a-11eb-960e-e71d10fa624b.png)

**Comment by robredpath** [comment]
This happens when a publisher includes HTML in their grant `description` field. I think that we do the right thing in displaying the HTML rather than trying to render it, as that's more secure, and helps to demonstrate the issues that anyone else trying to use the data is likely to come across. 

I've suggested that we address this in CoVE (see also #448), but this is quite a rare thing to see.

**Comment by BibianaC** [comment]
Thanks @robredpath . I will close this one as it is duplicated.
