### ISSUE TITLE
No Results page improvement ideas

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#744]
Following on from #622

I think we could spent a little time thinking through what else we can tell people who've ended up on this page. 

Currently, it's very terse. We could write some more verbose, and reassuring, copy and either put it on the help site (the error -> get help interaction can be quite reassuring) or make the page itself more helpful. 

We could link to the [instructions about using the search bar](https://help.grantnav.threesixtygiving.org/en/latest/search_bar.html#) although they rapidly get into advanced search, which might confuse people. 

We could just give some examples, as well!

**Comment by odscjames** [comment]
Also to discuss: In #634 we realised there are several problems with displaying the search options boxes on the left hand side - different boxes don't behave consistently at the moment. In #634 we are going to remove them for now (as fixing them properly involves some discussion about what we actually want for this, and doing it will almost certainly be some fiddly work). Maybe this ticket could discuss if the no results page should have search boxes in the left column, and if so, how should they behave?

**Comment by robredpath** [comment]
> . Maybe this ticket could discuss if the no results page should have search boxes in the left column, and if so, how should they behave?

Definitely. Interesting question. If you can remove filters to get some results back, then that might suggest that we should just hide the UI for adding more constraints to the search. But, if you've got quite a well-set-up set of filters, removing them without noting what you're doing might feel quite unwelcome. 

I'd be interested to understand if we could highlight the most recent filter to be added, so that the user has an effective undo option and understands what they did.

**Comment by mariongalley** [comment]
OK so just for my own clarity I'm going to summarise what we've done so far and what's still TBC/To do:

- In **"Filters applied" section isn't shown if there are no results** #622
  - The filters applied to the search were added below the "No results" header but above the explanatory bullets
- In **"No Results" page isn't very helpful** #634, I think?
  - We added the two following bullets to the "Try something like" explanation:
    - Removing some filters
    - To clear your search, click here (link back to homepage)
  - We removed the left hand column entirely on the no results page
    - I'm confused about this one. What's the left-hand column, is that where you could previously modify a somewhat arbitrary list of filters including Amount?
- In **Make the invalid search input page more helpful** #748 (TO DO)
  - We plan to make similar improvements to a slightly different error page which is the results page for _invalid_ searches rather than searches that return no results

In **this ticket**, we're considering:
- > We could write some more verbose, and reassuring, copy and either put it on the help site (the error -> get help interaction can be quite reassuring) or make the page itself more helpful.
  - Yeah I'd be happy to link to the help site. Do you have anything in mind for more reassuring copy? A cursory search for what other sites do suggests they sometimes say "Sorry," before "We can't find what you're looking for", but I haven't seen vary many be more verbose than that. Maybe the attention span of our users is a bit longer than a typical eCommerce site visitor!
- > We could link to the instructions about using the search bar although they rapidly get into advanced search, which might confuse people.
  - I agree, I think it would be ideal if one of the bullet points linked to some instructions (and I think we should do the same on the invalid search input page).
- > Maybe this ticket could discuss if the no results page should have search boxes in the left column, and if so, how should they behave
  - I'm confused about this one too. Does this relate to the the left-column elements which we removed above, or is this about adding something completely new to that space?

**Comment by mariongalley** [comment]
Also David mentioned that any outstanding work on the No Results page isn't a priority for the current upgrade and can be done later. I think the same applies to the invalid results page.

**Comment by robredpath** [comment]
> Do you have anything in mind for more reassuring copy? 

How about something along the lines of:

## 0 Results

Your search terms and filters don't match any of the grants in GrantNav. This can happen for a few reasons.

If you're searching for something specific, try using fewer search terms or consider searching for alternative ways to describe whatever you're searching for. 

If you've just applied a new filter, then the value that you've just selected doesn't match any results. Try removing the filter, and trying again. 

If you've just started a new search, then any filters that you previously had set are still applied. Click here to clear all filters.

It's always worth checking your spelling, as well - GrantNav doesn't try to correct your input or suggest alternatives. If what you're searching for may be spelled in multiple ways, see our guide to searching for advice on how to use the search bar to look for this. 

> I'm confused about this one too. Does this relate to the the left-column elements which we removed above, or is this about adding something completely new to that space?

This is about the elements that we removed. We *could* put all of the filters on the left-hand side, if we wanted to - this would be good if, for example, someone had clicked on a year with no results - they could go back to the same UI that they made the mistake in, and undo it. As it stands, they now have a different mechanism to remove the filter than the one they used to add the filter. 

However, each of the elements has their own issues when there are no results, which is why we didn't display most of them before. And, when there aren't any results, the page feels quite different, so it's not obvious that users would understand immediately that they could use the same UI to undo whatever they had just done. What we've done here is make the page more like an error page with some specific tools to fix your error, which IMO is preferable to trying to recreate the normal filter interface, but just with no results.

**Comment by mariongalley** [comment]
I'm not sure I think the lengthier text is helpful. It's definitely friendlier but it takes longer to read, and when people land on a no results I'd expect them want to get away from that page as quickly as possible.

Maybe we can just add links to the Help site and the Search bar instructions and leave it at that?

**Comment by mariongalley** [comment]
Closing issue
