### ISSUE TITLE
Search summary: Add earliest year and latest year

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#769]
Add earliest year and latest year to the 'above-the-fold' stats along side funders, recipients, etc.

**Comment by Lathrisk** [comment]
This is the current appearance of the `Earliest year` and `Latest year` summary stats. The copy is up for grabs. I used what was described in this issue, but I wrote this issue. Also considered `Earliest grant` or variations on that.

Does this look ok?

![summary-stat-years](https://user-images.githubusercontent.com/517804/125303379-aadefb80-e324-11eb-822a-f7313f360dfb.png)

**Comment by Lathrisk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Summary Stats updates: Years](https://trello.com/c/J76566pW/186-summary-stats-updates-years)

**Comment by mariongalley** [comment]
@drkane @KDuerden Any preference on the wording? Could do:
- Most recent grant/Oldest grant: that's what it says now in the highlighted grants, but since we're only displaying the year it might be inaccurate
- Earliest year/Latest year: This is what Jared has suggested, it's succinct, should be fairly obvious from context what years we're referring to
- Earliest grant year/Latest award year: This would be most accurate, but maybe a bit long

**Comment by KDuerden** [comment]
Earliest grant award / Latest grant award?

Is there any scope for the date to include the month and year?

**Comment by Lathrisk** [comment]
@KDuerden @mariongalley 
Yes, I think we have access to the full date. This was with existing code:

![full_date](https://user-images.githubusercontent.com/517804/125424445-88899a88-5897-426d-94ae-1582fa448542.png)

 Would just month and year be preferable?

**Comment by KDuerden** [comment]
I would prefer a full date, as it helps with results within a single year.
If others are ok with including full dates, I think the label could even be updated to:
Earliest grant:
Latest grant:
