### ISSUE TITLE
grantProgramme: title_keyword appearing in 'Grant Details' table rather than 'Additional data'

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#795]
**Describe the bug**
grantProgramme: title_keyword appearing in 'Grant Details' table but as this is strictly speaking data that is added as part of the GrantNav process, this should appear in 'Additional data' instead.

For example: https://grantnav.threesixtygiving.org/grant/360G-phf-37512

**To Reproduce**
1. Go to any grant record
2. Scroll to bottom of grant detail table
3. See grantProgramme: title_keyword value

**Expected behavior**
The added data should not appear in the Grant Details table.

**Screenshots**
![image](https://user-images.githubusercontent.com/20462640/141262637-9c7809d5-27af-4e2c-9cc4-2de1a24c31d0.png)

**Comment by michaelwood** [comment]
Think this field just needs to be added to https://github.com/ThreeSixtyGiving/grantnav/blob/master/grantnav/frontend/templatetags/frontend.py#L57

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grantnav: grantProgramme: title_keyword appearing in 'Grant Details' table rather than 'Additional data'](https://trello.com/c/F2qpCSOR/223-grantnav-grantprogramme-titlekeyword-appearing-in-grant-details-table-rather-than-additional-data)

**Comment by odscjames** [comment]
Now live
