### ISSUE TITLE
Grant programme title option in main search doesn't seem to work

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#807]
**Describe the bug**
When selecting "Grant Programme Title" option via the main search there are no results. When searching for the same term or phrase using the Grant programme filter on left side there are results.

It appears that the grant programme title search isn't working.

**To Reproduce**
1. If you go to https://grantnav.threesixtygiving.org/search?query=migrants+and+refugees&default_field=grantProgramme.title_keyword&sort=_score+desc
There are zero results
2. If you go to https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&grantProgramme=Migrants+and+Refugees
There are 422 results

**Expected behavior**
I would expect the main search with grant programme selected to give the same or similar results to using the left filter, in a similar way that Recipients and Locations in the main search will mirror results in their respective left filters.

For example a search for Bristol via main search
https://grantnav.threesixtygiving.org/search?query=bristol&default_field=additional_data.recipientLocation&sort=_score+desc

And via filter: https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&recipientDistrictName=City+of+Bristol

Have the same results of 4,269

If it is not possible to get the grant programme filter in the main search to work as intended, the option should be removed.

**Additional context**
I can't remember if I tried to use the grant programme filter in the main search before, so I can't comment on whether this is a recent development/issue.

**Comment by robredpath** [comment]
This is happening (I think!) because we're using the `keyword` type to create the field that we use for both the facet and the text search (see https://github.com/ThreeSixtyGiving/grantnav/blob/master/dataload/import_to_elasticsearch.py#L186-L190 )

The `keyword` type is used for exact-match (or "term") searches - the example in [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html) is for ISBNs for books. However, these searches are very exact - even case-sensitive. For example [searching for "Migrants and Refugees" in Grant Programme Titles](https://grantnav.threesixtygiving.org/search?query=%22Migrants+and+Refugees%22&default_field=grantProgramme.title_keyword&sort=_score+desc) returns 422 results, but ["Migrants and refugees"](https://grantnav.threesixtygiving.org/search?query=%22Migrants+and+refugees%22&default_field=grantProgramme.title_keyword&sort=_score+desc) produces none. 

There's a couple of ways that we can fix this, now that we know what it is, and I'll leave it to the devs to work out which way to go!

**Comment by mariongalley** [comment]
@KDuerden For the purposes of the data surgery, if we can't get this fixed in time, is it OK to say that it should work and we're getting it fixed ASAP? I think it should be possible to get it fixed in time though. @robredpath the surgery on How to use GrantNav is on the 14th Dec.

**Comment by KDuerden** [comment]
Yes as it works but only very precisely, we can explain that and suggest people use the filter for the time being.

**Comment by mariongalley** [comment]
@KDuerden Would you like to test this to confirm it works ahead of your data surgery?

**Comment by michaelwood** [comment]
This has just been deployed. Note that previous test links to programme title searches will not work as we needed to update the field name.

**Comment by KDuerden** [comment]
Yes this works now! - https://grantnav.threesixtygiving.org/search?query=%22covid+response%22&default_field=grantProgramme.title&sort=_score+desc

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Programme title search not returning results](https://trello.com/c/Shzhdq15/232-programme-title-search-not-returning-results)
