### ISSUE TITLE
Improve design of the funder/recipient cards on the Funders/Recipients pages

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#824]
### Improve design of the funder/recipient cards on the Funders/Recipients pages

- It's clear how the world will be different when the work is completed

It should be easier to see that each row corresponds to a currency and that each column has the same label

- It's clear what will and won't be done

Contents of what is displayed will not change. Design will be improved.

- Any uncertainty, assumptions, dependencies or constraints are recorded

Not clear what's the best way of doing this. Repeated labels seems to call for it to be a table, but having a table within a card could be messy.

- There's an order-of-magnitude estimate of how long it will take

- The work's been approved by someone at ThreeSixtyGiving

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

**Comment by mariongalley** [comment]
- At minimum, we need to change the labels to not be below the number they are labelling, as this is quite difficult to read.
- Suggest removing Smallest Amount as it is sometimes misleading (£0, negative values) and not all that useful as long as you have the max and average
- Suggest displaying instead the most recent award date on each funder/recipient card (should also add sort by latest award date, will add this to #830

Feedback from the team is that it's hard to view the list of funders/recipients as a list because the cards are quite tall, so you can only see 3-5 orgs at once depending on screen size, and the org names break up the values so you can't easily skim down the list of total grant amounts for e.g.
The pages are very useful for searching, but the lists are helpful in and of themselves, e.g. if you sort funders by Amount, you can skim the list and see how quickly it drops off after the first few gov funders.

**Comment by michaelwood** [comment]
I've re-ordered the labels and removed some of the extraneous padding/whitespace. I also removed the word "Amount" which saves some wrap space. I fixed the currency name only showing GBP to if there are multiple currencies.

I experimented with having the top labels only appear once but realised the responsive design means that the grid can re-order itself which would make the alignments very confusing.  A table would be logical but I don't think we have a design for that nor would it be responsive. 

A possible idea would be to have a default filter setup as GBP ticked and only show the filtered currency in the results.

**Comment by mariongalley** [comment]
OK, this all looks good. Still to do:

- removing Smallest Amount
- displaying instead the most recent award date on each funder/recipient card
- Turning the Grant Search link into a nicely styled button

**Comment by michaelwood** [comment]
> * removing Smallest Amount
> * displaying instead the most recent award date on each funder/recipient card
> * Turning the Grant Search link into a nicely styled button

Done.

The only caveat is that we only know the most recent award date on a per organisation basis rather than a per currency basis if that was what was expected. It sits in the right hand column of the result, this is similar design wise to grants results.

One other thing I fixed on the way that was bugging me was the no results pages for grants, recipients and funders:

- "Try something like: To clear your search, click here"  to "Or clear your search" link that its not nested under "try something like" 
- The link for clear your search on grants page now goes to grants search rather than home page
-  Grant, Funder and Recipient searches I changed " did not match any [grant/funder/recipient] records". 

On the home page is "Funder search" "Recipient search" and "see all grants" correct for the three buttons? I think the "See all grants" could do with now being "Grants search" , or the other two could be "See all Funders" , "See all Recipients" ?

**Comment by michaelwood** [comment]
>
> @michaelwood I like "Funder search" and "Recipient search" as those pages are distinctly more search-like than they were previously, but I agree "Grants search" makes a lot more sense than "See all grants", as no one's actually scrolling through 650,000 grants on that page...

Great, that's now deployed to the dev site.
