### ISSUE TITLE
Update values in GrantNav location filters to match the values used in Insights

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#869]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

GrantNav filters include strange values that are not widely understood, for example there is a region called South East Coast.

**Describe the solution you'd like**

Make GrantNav use the same values as Insights in the location filter(s)

**Describe alternatives you've considered**

Insights currently includes filters for old areas, and their successors. When publisher includes postcode it's matched to current areas, but any publisher sharing data in the form of geocodes only will nest under the district for that code. We considered attempting to resolve this issue at the datastore level rather than reproducing it in GrantNav. We would still like to do this, but it will take some thought about how to handle older areas, so for now getting GrantNav to match current Insights behaviour is a big improvement.

**Additional context**

**Comment by mariongalley** [comment]
Odd value seems to still be showing in Live GrantNav:


![Image](https://user-images.githubusercontent.com/82958988/211288574-75133095-4c14-4e74-a90c-f539270f6318.png)

**Comment by michaelwood** [comment]
After _a lot_ of head scratching as to how this is happening, it's actually quite obvious, The 360G-landaid - "Awarded grants since 2013 to March 2019" where these grants come from is offline . The datastore has fallen back to the last good download from 2022-12-14 which is sufficiently long ago that the additional_data (with the relevant geo fields) is from when we hadn't gotten all the location region things changed/sorted. 

This will fix itself either by the publisher fixing the link or the data falling out of the datastores' database in the next few days.

**Comment by mariongalley** [comment]
@KDuerden Mystery solved!

**Comment by KDuerden** [comment]
@mariongalley apologies I knew about this, and thought I had mentioned it! The file is back online now and the issue is fixed.
