### ISSUE TITLE
Funder and Recipient pages missing downloads

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#897]
**Describe the bug**
Funder and Recipient pages in the org pages GN don't have option to download CSV anymore.

**To Reproduce**
http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/funders
http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/recipients

**Expected behavior**
The funder and recipients download is useful (and in particular the Funder list is used in 360Giving's own work to monitor the data, and it is needed for our board reporting etc).

We would like the option to download to be reinstated.

**Screenshots**
![image](https://user-images.githubusercontent.com/20462640/201101969-c0218eaf-2ddf-43a7-a667-44e9b03ec343.png)

**Additional context**
The current behaviour of the download in live GN is they download all the data. The label currently says 'Export Search Data' results so the label may need updating depending on what is accurate for the behaviour of the download.

**Comment by michaelwood** [comment]
I've not found any sign of this functionality in the older version or in the design, so this would need to be developed as a new feature.

This is approx a 2 dev days of work.

It's slightly more involved than it might seem because we can't reuse any of the [existing csv/json download](https://github.com/ThreeSixtyGiving/grantnav/blob/Nov2022/grantnav/frontend/views.py#L97
) mechanisms because the data stored is 'organisation data' rather than 'grant data' and none of the file creation functions, unit tests or the field mappings (to csv/json) are applicable (grantnav's 'database' now has 3 types of data; recipients, funders and grants, with a special provenance json file providing publisher data).

**Comment by michaelwood** [comment]
One thing we could do as an interim is add the download icons when no filters/search is applied. That would re-use the functionality that exists on the https://grantnav.threesixtygiving.org/recipients | funders pages. I'm a little wary of doing that because that data is created by the grant data so won't necessarily reflect the same data that is being displayed.

**Comment by KDuerden** [comment]
> One thing we could do as an interim is add the download icons when no filters/search is applied.

This is the download that is needed for our stats. However if putting that functionality in sets up potential issues/unintended consequences, and a full solution is 2 x days then we should investigate getting this to get this data from the Datastore, via colab notebook instead.

**Comment by KDuerden** [comment]
> Using the datastore would be a more logical place to get the data

Yes, I'm happy to pursue getting the data that way.

**Comment by mariongalley** [comment]
For MVP, will do this solution:
> The download links on the https://grantnav.threesixtygiving.org/recipients and https://grantnav.threesixtygiving.org/funders for csv and json downloads are static links and could be added to somewhere like the /datasets page until they're no longer used (no icons just links).

Then will work on a datastore-based fix later. Ideally Michael would review Tom's process for getting those stats and produce the data Tom needs without it needing as much transformation work on Tom's part.

**Comment by michaelwood** [comment]
Links to those downloads are now on [/datasets](http://grantnav.360dev1.vs.mythic-beasts.com/datasets/)
The actual download link is the same so this hopefully we allow Tom's process to remain the same for now.

[New issue to track a download search results feature](https://github.com/ThreeSixtyGiving/grantnav/issues/904)
