### ISSUE TITLE
Set up redirects from old Funder & Publisher pages to new Org pages

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#899]
- Existing Funder pages' URLs are in the format `.../funder/org-id`
    - They need to be redirected to the funders' new org pages' URLs which will be in the form `.../org-id`
- Existing Publisher pages will disappear. They currently take the form `.../publisher/prefix`
    - They need to be to be redirected to the new style org pages, which will be in the form `.../org-id` for Funder Publishers, or the form `.../prefix` for non-Funder Publishers.

**Comment by michaelwood** [comment]
This is in progress and has been pushed to dev. I'm having some difficulty adapting the tests so that they continue to work with some of those awkward corner cases such as `/org/XI-GRID-grid.5292.c` where it needs to not parse that as a file location, I don't know how important that is anymore as I can't find the data in the live grantnav that prompted that test.

**Comment by KDuerden** [comment]
> I don't know how important that is anymore as I can't find the data in the live grantnav that prompted that test.

I don't understand the implication of this. There is a funder who's own org ID has is XI-PB-gb/bord-na-gaidhlig so these redirects are important for this case.

**Comment by michaelwood** [comment]
@KDuerden I was just making sure we don't lose the correct handling of those awkward org-ids when moving the test cases to use the /org version. I've also added a test case for the redirects. The changes are now on the dev server.
