### ISSUE TITLE
Org pages copy updates

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#905]
see planio 33741

**Comment by mariongalley** [comment]
I've done a cross reference of the copy updates doc and dev GN, the only things remaining are:

- the Learn More About Organisations button is still a small i instead of a main button on Org pages
- the Funders count has not yet been added to the As Recipient section
- Need to remove the double hyperlinking of the publisher page for non publisher funders in the As Publisher section
- Need separation of other names with semicolons instead of commas on the org search views and the org page view
