### ISSUE TITLE
Ward name and geocodes no longer indexed for Location search

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#943]
**Describe the bug**
In the GrantNav update to use beneficiary location data (due to go live 2022-12-14) the ability to search within the location for Ward names and Geocodes has disappeared.

Although this data is not part of the location filters, if you know the name or geocode of a ward, you can get results for grants that include that data (either because it was shared directly as Ward codes, or from the postcode lookup).

[Search for Streatham South Ward](https://grantnav.threesixtygiving.org/search?query=%22Streatham+South%22&default_field=additional_data.recipientLocation&sort=_score+desc)

![image](https://user-images.githubusercontent.com/20462640/207363289-d5a270f7-f754-4acd-b857-8f7e90db25f6.png)

It also works with the geocode: [https://grantnav.threesixtygiving.org/search?query=E05000431&default_field=additional_data.recipientLocation&sort=_score+desc](https://grantnav.threesixtygiving.org/search?query=E05000431&default_field=additional_data.recipientLocation&sort=_score+desc)

The same results in the DEV GN (soon to be live) are blank

![image](https://user-images.githubusercontent.com/20462640/207365787-f46dd4ed-abba-4bc5-b1f6-c1e48981e399.png)

**Expected behavior**
It would be good to have the functionality restored, for the grants that have the relevant data.

**Additional context**
Additional context for this, it looks like the search results download includes complete Ward data even when the filters are using beneficiary location. This means the functionality to allow for name or geocode searching by Ward probably needs to resolve potential contractions for data with both Beneficiary location at higher levels and Recipient Location at postcode or Ward level.

**Comment by KDuerden** [comment]
To expand on the point raised in the additional context. 

I think because the Ward data in the export includes data based on recipient location even in cases where the beneficiary location is being used as a priority, we can't index the Ward name/code field to the search until that issue is resolved. Otherwise the results based on Ward details could be in contradiction to the results in the District or Region details.

**Comment by michaelwood** [comment]
Hmm yes I imagine that level of ward data was found via some kind of postcode lookup on the recipient organization which we're not doing because the data has supplied a beneficiaryLocation. So this is somewhat expected. Possibly the lat/lng could be used if we had that data.

In  https://grantnav.threesixtygiving.org/grant/360G-SE-2020018032LOTT_2020-06-09  there are 4 beneficiary locations for 

```json
	"beneficiaryLocation": [
		{
			"name": "SW16 5RP",
			"latitude": 51.419619,
			"longitude": -0.13209,
			"countryCode": "GB"
		},
		{
			"name": "Streatham",
			"geoCode": "E14000978",
			"geoCodeType": "WPC"
		},
		{
			"name": "Lambeth",
			"geoCode": "E09000022",
			"geoCodeType": "LAD"
		},
		{
			"geoCode": "E01003145",
			"geoCodeType": "LSOA"
		}
	],
```

The Streatham E14000978 specified is the [Westminster parliamentary constituency](https://findthatpostcode.uk/areas/E14000978.html) and we don't appear to have WPC data in the location look up, the other locations do get looked based on beneficiary data and result in:

```json
"locationLookup": [
		{
			"ewcd": "K04000001",
			"ewnm": "England and Wales",
			"gbcd": "K03000001",
			"gbnm": "Great Britain",
			"ukcd": "K02000001",
			"uknm": "United Kingdom",
			"ladcd": "E09000022",
			"ladnm": "Lambeth",
			"rgncd": "E12000007",
			"rgnnm": "London",
			"ctrycd": "E92000001",
			"ctrynm": "England",
			"source": "beneficiaryLocation",
			"utlacd": "E09000022",
			"utlanm": "Lambeth",
			"areacode": "E09000022",
			"areaname": "Lambeth",
			"areatype": "la",
			"sourceCode": "E09000022"
		},
		{
			"ewcd": "K04000001",
			"ewnm": "England and Wales",
			"gbcd": "K03000001",
			"gbnm": "Great Britain",
			"ukcd": "K02000001",
			"uknm": "United Kingdom",
			"ladcd": "E09000022",
			"ladnm": "Lambeth",
			"rgncd": "E12000007",
			"rgnnm": "London",
			"ctrycd": "E92000001",
			"ctrynm": "England",
			"source": "beneficiaryLocation",
			"utlacd": "E09000022",
			"utlanm": "Lambeth",
			"lad17cd": "E09000022",
			"areacode": "E01003145",
			"areaname": "Lambeth 034D",
			"areatype": "lsoa",
			"latitude": 51.418567399945935,
			"msoa11cd": "E02000651",
			"msoa11nm": "Lambeth 034",
			"ttwa11cd": "E30000234",
			"ttwa11nm": "London",
			"longitude": -0.13141778914605,
			"sourceCode": "E01003145",
			"msoa11hclnm": "Streatham Common",
			"ladcd_active": "E09000022",
			"ladnm_active": "Lambeth"
		}
	],
```

The first location lookup is what is used to filter on (as in insights) . The search searches on a special `recipientLocation` field in `additional_data` which is a space separated string of locations and geocodes that were found.

Looking at the lat/lng does show that this is likely to be in https://findthatpostcode.uk/areas/E05000431.html but I don't think we have any mechanism to place it there currently.

**Comment by mariongalley** [comment]
> I've just had a flash back to us talking about changing the search on grantnav to read "all locations" or something like that so that we can explain away why it may be possible to get conflicting / multiple locations for a grant. Is that the route that would be good to go down here?

Yes me too! I'm OK with getting multiple locations for a grant if it's consistent i.e. it always searches All Locations rather than sometimes Recipient or Beneficiary only and sometimes across both. I decided not to pursue renaming as I think Locations does a sufficient job of indicating it's both Recipient and Beneficiary.

In any case, I agree with Katherine if would be good to still be able to input a Ward name in the Locations-filtered-search-bar and get relevant results, either based on All Locations or Best Available Location.

**Comment by michaelwood** [comment]
Okay understood. I'm not discerning any action needed at this point, let me know if I've missed it.

**Comment by mariongalley** [comment]
> In the GrantNav update to use beneficiary location data (due to go live 2022-12-14) the ability to search within the location for Ward names and Geocodes has disappeared.
>
> Although this data is not part of the location filters, if you know the name or geocode of a ward, you can get results for grants that include that data (either because it was shared directly as Ward codes, or from the postcode lookup).

Michael's understanding is that the Location filtered search bar does work with Ward data, but because it uses "Best Available" and most Beneficiary Locations don't have Ward level data, this returns fewer results than previously. @michaelwood to test if that's not working correctly.

An alternative is to get the search bar Locations filter to search across all locations instead of just best available, but I don't think that's what you wanted @KDuerden ?

**Comment by michaelwood** [comment]
I had a check again and ward information is only available via  `additional_data: recipientOrganizationLocation: ward*`  which comes from the recipientOrganization postcode lookup. This was actually omitted by accident due to the field name change so can be easily be added if we want the mix of beneficiaryLocation and recipientOrgnization (option 1).

option 1:

```python
grantnav_search_location_field = best_location + additional_data: recipientOrganizationLocation: ward*
```
Where `best_location` is our  beneficaryLocation location data if possible falling back on recipientLocation location data.

option 2:

We could also only include `additional_data: recipientOrganizationLocation: ward*` if all the rest of the best available location also comes from the recipientOrganization.

Something like:
```python 
if best_location_source is "beneficiaryLocation":
  grantnav_search_location_field = beneficaryLocation location data
else if best_location_source is "recipientOrganization":
  grantnav_search_location_field = recipientOrgnization location data + additional_data: recipientOrganizationLocation: ward*
```

**Comment by KDuerden** [comment]
Thanks for investigating further. 

For the now live version of GrantNav - option 2 is the one that aligns with the process of prioritising beneficiary location and so it's my preference for now. 

However, I'm still keen for longer term to develop the ability to search with either recipient or beneficiary location in GN - so would going with option 2 now create any barriers for progressing with that phase 2 work?

**Comment by michaelwood** [comment]
Option 2 now deployed ^

**Comment by michaelwood** [comment]
I think this original issue is now resolved.

**Comment by mariongalley** [comment]
@michaelwood [Ward search](https://grantnav.threesixtygiving.org/search?query=%22Streatham+south%22&default_field=%2A&sort=_score+desc) seems broken again - shall I open a new issue?

**Comment by KDuerden** [comment]
To confirm, there is no longer any data in the download under the Recipient Ward Name or Geocode headings.
