### ISSUE TITLE
Display Grants to Individuals codelist values on the Grant page

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#976]
Suggested method of displaying this is to put the string/human readable version of the code in brackets:

![image](https://user-images.githubusercontent.com/493697/220652707-c733c64a-4db1-4166-b2f6-996188832760.png)

**Comment by mariongalley** [comment]
Oh yes I like this. What do you think @KDuerden ?

**Comment by KDuerden** [comment]
I like it! But I think this will also cause confusion for publishers because our guidance is very strictly - codes only - but it will seem like other publishers are including the text & codes.

I don't think this is a barrier to this approach, but we need to be able to explain in situ and also in our guidance why these things look different in our tools. 

This is also raising a question in my mind about the impact on the data in GrantNav downloads - eg is this bringing together two separate sources of data and visualising - and so in the Additional data it will just be the names - or would it be this code + name data?

**Comment by michaelwood** [comment]
We could also do something more like:

Option 2

![Screenshot from 2023-02-22 17-35-03](https://user-images.githubusercontent.com/493697/220709903-b548fd36-0734-4300-be8d-d9cc56b46183.png)

With the link going to https://standard.threesixtygiving.org/en/latest/technical/codelists/#the-codelists-used-in-the-standard 

Option 3

![image](https://user-images.githubusercontent.com/493697/220710995-e8b9cde4-aa12-42ba-8904-140c75b46709.png)
(with or without the parenthesis) 

If we had bootstrap I'd probably be suggesting a https://getbootstrap.com/docs/5.3/components/popovers/ . Possibly something we could get added to the 360ds for "small hints/help" for future type things

**Comment by mariongalley** [comment]
@michaelwood Thanks for thinking further about this - I don't think any of the options fully mitigate the issue of us adding information that wasn't shared by the publisher, but I really like option 2 because it explains where we got the codelist values from. It would be even better if it could link to the [specific codelist in the guidance](https://standard.threesixtygiving.org/en/latest/technical/codelists/#regrant-type) (this will become increasingly useful as we proliferate codelists).

I think we can address for former issue by updating the teal 'where is this data from' box to say something like:

"This data was originally published by [publisher]. You can hover over codes from [standard codelists](https://standard.threesixtygiving.org/en/latest/technical/codelists/) to see the user-friendly name provided by 360Giving. If you need to report a problem in the data please contact [publisher] directly, see their _GrantNav publisher page_ for more information."

**Comment by michaelwood** [comment]
Great, have implemented that, example (test data) http://grantnav.360dev1.vs.mythic-beasts.com/grant/360G-FoundationScotland-A377940

**Comment by KDuerden** [comment]
Thanks for developing this alternative approach - which is really nice!

Could this be implemented for regranting and location scope as easily? I think we could limit this function to our managed codelists, eg we don't need to start pulling the human readable names for currency or countries (not least because I don't think they are included in our standard - it's just the enum codes)

**Comment by mariongalley** [comment]
@KDuerden Agree - the only place I can see it being an issue is the geocode types list, which isn't validated - this means there will be codes that don't appear in the hyperlinked list. Maybe that's fine?

**Comment by KDuerden** [comment]
I had the same thought, it would be fine if only the properly used ones have the hyperlink! 

But can we hold off on that, because I'm just noticing that there is at least one non-unique code with different names WD is named 'Electoral Divisions' and 'Electoral Wards'. Might need to do some housekeeping before we start integrating the names to avoid confusion.

**Comment by michaelwood** [comment]
I had a similar thought that we can expand this for older codelists, ([regrantType is already in there, just wasn't any test data showing it](https://github.com/ThreeSixtyGiving/grantnav/blob/d7bfe8ca6b37c63f102380ba00d27d0e21c18541/grantnav/frontend/templates/grant.html#L88-L109)). 

The code is ready for future codelist friendly name work when we have resolved the two issues with the other codelists files. I added a [comment in the code](https://github.com/ThreeSixtyGiving/datastore/blob/master/datastore/additional_data/sources/codelist_code.py#L6) . https://github.com/ThreeSixtyGiving/standard/issues/349 and https://github.com/ThreeSixtyGiving/standard/issues/348

**Comment by mariongalley** [comment]
Question about: "You can hover over codes from standard codelists to see the user-friendly name provided by 360Giving." - I assume that will appear on all grants rather than just ones that include codes?

I think this is probably fine if so, just want to check @michaelwood

**Comment by michaelwood** [comment]
> Question about: "You can hover over codes from standard codelists to see the user-friendly name provided by 360Giving." - I assume that will appear on all grants rather than just ones that include codes?
> 
> I think this is probably fine if so, just want to check @michaelwood

Yes currently that is the behaviour. It is possible to make that conditional but it's a bit gnarly (it would need to be a hard-coded list of all the possible fields that could be codelists and then a check on each to see if they have values.
